### ISSUE TITLE
grape fails with java.lang.reflect.InvocationTargetException caused by groovy.lang.MissingMethodException

### ISSUE THREAD

**Issue by allanlewis** [groovy/docker-groovy#24]
I'm currently unable to run `grape` in `groovy:2.4.13-jre8-alpine`:
```
$ docker run --rm groovy:2.4.13-jre8-alpine grape
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
Caused by: groovy.lang.MissingMethodException: No signature of method: groovyjarjarcommonscli.Options.getOptionProperties() is applicable for argument types: (java.lang.String) values: [D]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.tools.GrapeMain.run(GrapeMain.groovy:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:925)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:908)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:412)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at org.codehaus.groovy.tools.GrapeMain.main(GrapeMain.groovy)
	... 6 more
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:12:17 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:14:50 2017
  OS/Arch:	linux/amd64
  Experimental:	false
$ docker image ls groovy:2.4.13-jre8-alpine
REPOSITORY          TAG                  IMAGE ID            CREATED             SIZE
groovy              2.4.13-jre8-alpine   34ce9830b507        4 weeks ago         127MB
```

**Comment by allanlewis** [comment]
This seems to be the case for all the JRE variants of the image.

**Comment by allanlewis** [comment]
Only the Groovy 2.5 images seem to work:
```
$ parallel -k --tag "docker run --rm groovy:{1}-{2} grape |& head -n1" ::: 2.4 2.5 2.6 3.0 ::: jre jdk 
2.4 jre	java.lang.reflect.InvocationTargetException
2.4 jdk	java.lang.reflect.InvocationTargetException
2.5 jre	usage: grape [options] <command> [args]
2.5 jdk	usage: grape [options] <command> [args]
2.6 jre	java.lang.reflect.InvocationTargetException
2.6 jdk	java.lang.reflect.InvocationTargetException
3.0 jre	java.lang.reflect.InvocationTargetException
3.0 jdk	java.lang.reflect.InvocationTargetException
```

**Comment by allanlewis** [comment]
The same applies for the Alpine variants:
```
$ parallel -k --tag "docker run --rm groovy:{1}-{2}-alpine grape |& head -n1" ::: 2.4 2.5 2.6 3.0 ::: jre jdk
2.4 jre	java.lang.reflect.InvocationTargetException
2.4 jdk	java.lang.reflect.InvocationTargetException
2.5 jre	usage: grape [options] <command> [args]
2.5 jdk	usage: grape [options] <command> [args]
2.6 jre	java.lang.reflect.InvocationTargetException
2.6 jdk	java.lang.reflect.InvocationTargetException
3.0 jre	java.lang.reflect.InvocationTargetException
3.0 jdk	java.lang.reflect.InvocationTargetException
```

**Comment by allanlewis** [comment]
I've tried quite a lot of image tags and 100% of Groovy 2.5 images don't error when executing `grape` whereas 100% of other images throw `java.lang.reflect.InvocationTargetException`.

**Comment by keeganwitt** [comment]
Thanks for reporting this.  I believe it's not an issue with my Docker images, but actually an issue with Groovy itself (I get the same error you did on Groovy from the zip file on Windows).  I'll investigate and follow up with the guys.

**Comment by keeganwitt** [comment]
Paul confirmed this is an issue.  I created [GROOVY-8438](https://issues.apache.org/jira/browse/GROOVY-8438) and will be adding more details to it soon.  I anticipate we'll have this fixed in 2.4.14.

**Comment by allanlewis** [comment]
Thanks, @keeganwitt!

**Comment by keeganwitt** [comment]
I guess I'll go ahead and close this -- unless someone can think of a workaround I could add before 2.4.14 ships.
