### ISSUE TITLE
Running groovyConsole possible (on Linux)?

### ISSUE THREAD

**Issue by rkrisztian** [groovy/docker-groovy#51]
Hi, tried this, which, in theory, should work, but seemingly not on this image:

```
$ xhost + 
access control disabled, clients can connect from any host
$ docker run -it --rm --network host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix groovy:latest groovyConsole
Sep 27, 2019 11:17:03 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:110)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)
Caused by: java.lang.UnsatisfiedLinkError: /opt/java/openjdk/lib/amd64/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.Toolkit$3.run(Toolkit.java:1636)
	at java.awt.Toolkit$3.run(Toolkit.java:1634)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at javax.swing.UIManager$getSystemLookAndFeelClassName.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at groovy.ui.Console.main(Console.groovy:245)
	... 6 more
```

**Comment by keeganwitt** [comment]
Sorry just noticed this.
The AdoptOpenJDK image I use as the base image doesn't include an X server. I'm no Xorg expert, but don't you need to do more than just mount a directory that XOrg is in (I assume that's what's in /tmp) to run X?

**Comment by keeganwitt** [comment]
Closing issue as stale. If you believe this should be reopened, please comment.

**Comment by roddsrod** [comment]
Gravedigging this one because I stumbled on the same issue and leaving here the solution that worked for me in case it might be helpful to other internet travelers.

Actually there are 2 approaches:

**Option 1: Create a new image with Docker commit**

Install packages in a container:
```
docker run --user root -it groovy:latest bash
apt update && apt install -y libx11-6 libxext6 libxrender1 libxtst6 libxi6 libxt6
```

In another terminal, find the container ID:
`docker ps`

Commit the changes to a new image:
`docker commit CONTAINER_ID groovy-x11`

Now you can use the new image with your libraries pre-installed:
`docker run --rm -it -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix groovy-x11 groovyConsole`


**Option 2: Create a Dockerfile**
```
FROM groovy:latest
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    libx11-6 libxext6 libxrender1 libxtst6 libxi6 libxt6 \
    && rm -rf /var/lib/apt/lists/*
USER groovy
```
Then build and use it:
```
docker build -t groovy-x11 .
docker run --rm -it -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix groovy-x11 groovyConsole
```
