### ISSUE TITLE
Running a Groovy script reports error

### ISSUE THREAD

**Issue by lyjbupt** [groovy/docker-groovy#80]
docker run --rm -v "$PWD":/home/groovy/scripts -w /home/groovy/scripts groovy:latest groovy <script> <script-args>

WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Caught: java.io.FileNotFoundException: /tmp/hsperfdata_groovy/test.groovy (/tmp/hsperfdata_groovy/test.groovy)
java.io.FileNotFoundException: /tmp/hsperfdata_groovy/test.groovy (/tmp/hsperfdata_groovy/test.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Should I copy test.groovy into container before running the script?

**Comment by keeganwitt** [comment]
That shouldn't be necessary. I'm confused why I'm seeing `/tmp`. That's not what you specified in the arguments.

**Comment by lyjbupt** [comment]
Seems --user option is needed, hence close this issue.
