### ISSUE TITLE
Grapes error following update to Groovy 4.0.15

### ISSUE THREAD

**Issue by msneeden** [groovy/docker-groovy#96]
One of our Groovy scripts started failing (running via `groovy:latest`) about the time of the bump to `4.0.15`. Specifically, an error pulling dependencies...

```bash
Caught: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: org.apache.directory#groovyldap;0.1-SNAPSHOT: java.text.ParseException: http://javax.xml.XMLConstants/property/accessExternalSchema in file:/home/groovy/.groovy/grapes/org.apache.directory/groovyldap/ivy-0.1-SNAPSHOT.xml.original]
        at test.<clinit>(test.groovy)
```

This does not happen running outside of Docker using `4.0.15`. Also, the last passing image digest was `sha256:706be95dcdc8cfaf3ecac4fd939056e8e51c42816833d843495bae4d856db20b` which appeared to be running `4.0.14`:

```bash
docker run --rm  groovy@sha256:706be95dcdc8cfaf3ecac4fd939056e8e51c42816833d843495bae4d856db20b groovy -v
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
Groovy Version: 4.0.14 JVM: 17.0.8.1 Vendor: Eclipse Adoptium OS: Linux
```
with the first failure (for us) manifesting in `sha256:c55acb2ef512947741ae5d1f8ee5272b4af59274e43234343b36dcb218a8fc59`. As best as I can tell there's been no code or environmental changes on our end; we can reproduce it locally or in CI (Jenkins). At present, we're pinning our image back to `4.0.14`.

I've narrowed it down the following (to reproduce) - if you can see what we're seeing the following will fail against `groovy:latest` and succeed against `groovy:4.0.14`:

```bash
docker run --rm -v %cd%:/home/groovy/scripts -w /home/groovy/scripts groovy:latest groovy ./test.groovy
```
where the contents of `test.groovy` are:
```bash
@GrabResolver(name='apache-snapshot', root='http://repository.apache.org/snapshots/')
@Grab(group='org.apache.directory', module='groovyldap', version='0.1-SNAPSHOT')
import org.apache.directory.groovyldap.*
```

**Comment by keeganwitt** [comment]
Something broke in Groovy itself it seems.

```
$ sdk use groovy 4.0.15
$ rm -rf ~/.groovy/grapes/* && groovy grapeTest.groovy; echo $?
Caught: java.lang.AbstractMethodError
java.lang.AbstractMethodError
	at org.apache.ivy.util.XMLHelper.isFeatureSupported(XMLHelper.java:421)
	at org.apache.ivy.util.XMLHelper.trySetFeature(XMLHelper.java:439)
	at org.apache.ivy.util.XMLHelper.configureSafeFeatures(XMLHelper.java:343)
	at org.apache.ivy.util.XMLHelper.getDocBuilder(XMLHelper.java:267)
	at org.apache.ivy.util.XMLHelper.parseToDom(XMLHelper.java:252)
	at org.apache.ivy.plugins.parser.m2.PomReader.<init>(PomReader.java:129)
	at org.apache.ivy.plugins.parser.m2.PomModuleDescriptorParser.parseDescriptor(PomModuleDescriptorParser.java:140)
	at org.apache.ivy.plugins.parser.m2.PomModuleDescriptorParser.parseDescriptor(PomModuleDescriptorParser.java:123)
	at org.apache.ivy.core.cache.DefaultRepositoryCacheManager$MyModuleDescriptorProvider.provideModule(DefaultRepositoryCacheManager.java:846)
	at org.apache.ivy.core.cache.ModuleDescriptorMemoryCache.getStale(ModuleDescriptorMemoryCache.java:68)
	at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.getStaledMd(DefaultRepositoryCacheManager.java:863)
	at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.cacheModuleDescriptor(DefaultRepositoryCacheManager.java:1369)
	at org.apache.ivy.plugins.resolver.BasicResolver.parse(BasicResolver.java:541)
	at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:278)
	at org.apache.ivy.plugins.resolver.IBiblioResolver.getDependency(IBiblioResolver.java:557)
	at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:101)
	at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:192)
	at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:284)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:801)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:729)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:801)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:729)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:801)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:729)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:792)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:729)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:792)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:729)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:801)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:729)
	at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:607)
	at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:250)
	at org.apache.ivy.Ivy.resolve(Ivy.java:522)
	at grapeTest.<clinit>(grapeTest.groovy)
1
$ sdk use groovy 4.0.14
$ rm -rf ~/.groovy/grapes/* && groovy grapeTest.groovy; echo $?
0
```

**Comment by keeganwitt** [comment]
The only thing that stood out to me as possibly related was a bump to the Ivy version

https://github.com/apache/groovy/compare/GROOVY_4_0_14...GROOVY_4_0_15#diff-87e6fe6a086cec9825e72357099f0ae6b84800ea025c5aee97b6cc7088c6cd4dR29

**Comment by keeganwitt** [comment]
Looking at the Ivy [changes](https://github.com/apache/ant-ivy/compare/rel/2.5.1...rel/2.5.2#diff-3d8ea2dd66baeefe710dc8343e4773f533906252c68fdba5bd9e9a809c87f11b), it looks like https://github.com/apache/ant-ivy/commit/2be17bc18b0e1d4123007d579e43ba1a4b6fab3d might be related.

**Comment by keeganwitt** [comment]
I tried running with
```
-e JAVA_OPTS='-Divy.xml.allow-doctype-processing=true -Divy.xml.external-resources=LOCAL -Djavax.xml.accessExternalSchema=file,http'
```
According to https://github.com/apache/ant-ivy/blob/503aafc594b777ffb035a457ed341e31334c23a4/asciidoc/systemproperties.adoc#xml-parser-settings, this should restore the legacy behavior. https://docs.oracle.com/javase/8/docs/technotes/guides/security/jaxp/jaxp.html mentions the standard JAXP system property.

This didn't work.

**Comment by keeganwitt** [comment]
I think I've got a solution. Try this in your script

```groovy
@GrabResolver(name='apache-snapshot', root='http://repository.apache.org/snapshots/')
@Grab(group='org.apache.directory', module='groovyldap', version='0.1-SNAPSHOT')
@groovy.lang.GrabExclude(group = 'groovy', module = 'groovy')
```

**Comment by msneeden** [comment]
@keeganwitt looks like we got a winner, thanks!!
